# Note you can just comment out pytorch installation and install
# whatever version and CUDA you need from https://pytorch.org/get-started/locally/
name: llmw-lagrange
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
# -- Pytorch --
  - pytorch::pytorch=2.5.1
  - pytorch::pytorch-cuda=11.8 # 12.4
# -------------
  - datasets=3.6.0
  - tqdm=4.67.1
  - numpy>=2, <3
  - sentencepiece=0.2.0
  - pillow>=11, <12 # Some models might need this for AutoProcessor
  - pip
  - pip:
    - matplotlib>=3
    - huggingface_hub==0.36.0
    - accelerate==1.12.0
    - transformers==4.57.3
    - protobuf==6.32.0