name: llmw-lagrange
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch::pytorch=2.5.1
  - pytorch::pytorch-cuda=11.8 # 12.4
  - transformers=4.51.3
  - datasets=3.6.0
  - tqdm=4.67.1
  - numpy>=2, <3
  - sentencepiece=0.2.0
  - pillow>=11, <12 # Some models might need this for AutoProcessor
  - galois=0.4.6
  - pip
  - pip:
    - accelerate==1.7.0
    - huggingface_hub==0.33.0
    - protobuf==6.32.0